id: 6bdf8337887246ccb84e29c24719c194
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_184-Teaching_the_Practice_of_a_Bodhisattva-v2
  language: en
  author: ''
  volume: {}
